## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
git:
  depth: 99999999

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("SemialgebraicSets")); using Coverage; Coveralls.submit(process_folder()); Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
