## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
coveralls: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
notifications:
  email: false
git:
  depth: 99999999
