name = "SemialgebraicSets"
uuid = "8e049039-38e8-557d-ae3a-bc521ccf6204"
repo = "https://github.com/JuliaAlgebra/SemialgebraicSets.jl.git"
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
MultivariatePolynomials = "0.3"
julia = "1"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DynamicPolynomials"]
