name = "SemialgebraicSets"
uuid = "8e049039-38e8-557d-ae3a-bc521ccf6204"
repo = "https://github.com/JuliaAlgebra/SemialgebraicSets.jl.git"
version = "0.3.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CommonSolve = "0.2"
MultivariatePolynomials = "0.4.2"
MutableArithmetics = "0.3.1, 1"
julia = "1.6"
